name: dcmenv
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - backcall=0.2.0
  - ca-certificates=2024.2.2
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=2.0.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.29.2
  - ipython=8.12.0
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - libcxx=14.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.2.1
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.2.0
  - prompt_toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.9.18
  - python-dateutil=2.8.2
  - python_abi=3.9
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.4
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
    - anyio==4.3.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - async-lru==2.0.4
    - attrs==23.2.0
    - babel==2.14.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - certifi==2024.2.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - contourpy==1.2.0
    - cycler==0.12.1
    - defusedxml==0.7.1
    - exceptiongroup==1.2.0
    - fastjsonschema==2.19.1
    - fonttools==4.49.0
    - fqdn==1.5.1
    - h11==0.14.0
    - httpcore==1.0.4
    - httpx==0.27.0
    - idna==3.6
    - importlib-resources==6.1.1
    - isoduration==20.11.0
    - jinja2==3.1.3
    - json5==0.9.17
    - jsonpointer==2.4
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter-events==0.9.0
    - jupyter-lsp==2.2.2
    - jupyter-server==2.12.5
    - jupyter-server-terminals==0.5.2
    - jupyterlab==4.1.2
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.25.3
    - kiwisolver==1.4.5
    - markupsafe==2.1.5
    - matplotlib==3.8.3
    - mistune==3.0.2
    - nbclient==0.9.0
    - nbconvert==7.16.1
    - nbformat==5.9.2
    - notebook==7.1.0
    - notebook-shim==0.2.4
    - numpy==1.26.4
    - overrides==7.7.0
    - pandas==2.2.1
    - pandocfilters==1.5.1
    - pillow==10.2.0
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.43
    - pycparser==2.21
    - pydicom==2.4.4
    - pyparsing==3.1.1
    - pyqt5==5.15.10
    - pyqt5-qt5==5.15.12
    - pyqt5-sip==12.13.0
    - python-json-logger==2.0.7
    - pytz==2024.1
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - referencing==0.33.0
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.18.0
    - send2trash==1.8.2
    - sniffio==1.3.0
    - soupsieve==2.5
    - terminado==0.18.0
    - tinycss2==1.2.1
    - tomli==2.0.1
    - types-python-dateutil==2.8.19.20240106
    - tzdata==2024.1
    - uri-template==1.3.0
    - urllib3==2.2.1
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.7.0
